### ISSUE TITLE
テンプレートの型による処理の分岐部分の問題

### ISSUE THREAD

**Issue by habu1010** [rotildeof/NN_try#1]
テンプレートの型が int か double かによって処理を分岐するために、`typeid(type_keeper).name()`で得た文字列による分岐を行っているようですが、このメンバ関数が返す文字列は処理系により異なるため、環境依存のプログラムになってしまいます。
また細かい事を言うと、型の判定が実行時に行われるため、プログラムの処理速度が低下します。
テンプレートの型で処理を分岐したいのであれば、次のいずれかの方法を取るのが良いかと思います。

- 関数のオーバーロード
- テンプレートの特殊化

**Comment by rotildeof** [comment]
ありがとうございます。確かにtypeidの出力が解説サイトに載っている出力と違うから何か変だとは感じていました。
結局、関数のオーバーロードで分岐させることにしました。
テンプレートを使って書くのはあまり経験がないもので、勉強になります。
